### ISSUE TITLE
import error - looks like an opencv problem

### ISSUE THREAD

**Issue by exnx** [libffcv/ffcv#136]
Hi,

I was able to install ffcv, and just playing around with it, able to import ffcv.

However, somewhere along the line I got this import error:

```ImportError: libopencv_imgproc.so.405: cannot open shared object file: No such file or directory```

Does that look familiar to anyone?

Update:

For someone reason, my ffcv install broke, so I can't import ffcv.  I don't think I really did anything, except maybe install pytorchvideo since the last time ffcv worked.  Not sure why I can't import ffcv anymore.  In my conda list, ffcv is still there.  Here's the full error:

```
>>> import ffcv
OMP: Info #277: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/envs/ffcv-hippo11/lib/python3.8/site-packages/ffcv/__init__.py", line 1, in <module>
    from .loader import Loader
  File "/home/miniconda3/envs/ffcv-hippo11/lib/python3.8/site-packages/ffcv/loader/__init__.py", line 1, in <module>
    from .loader import Loader, OrderOption
  File "/home/miniconda3/envs/ffcv-hippo11/lib/python3.8/site-packages/ffcv/loader/loader.py", line 12, in <module>
    from ffcv.fields.base import Field
  File "/home/miniconda3/envs/ffcv-hippo11/lib/python3.8/site-packages/ffcv/fields/__init__.py", line 3, in <module>
    from .rgb_image import RGBImageField
  File "/home/miniconda3/envs/ffcv-hippo11/lib/python3.8/site-packages/ffcv/fields/rgb_image.py", line 15, in <module>
    from ..libffcv import imdecode, memcpy, resize_crop
  File "/home/miniconda3/envs/ffcv-hippo11/lib/python3.8/site-packages/ffcv/libffcv.py", line 5, in <module>
    import ffcv._libffcv
ImportError: libopencv_imgproc.so.405: cannot open shared object file: No such file or directory
```

**Comment by GuillaumeLeclerc** [comment]
Hello,

What happens if you reinstall `ffcv` with pip ?
