### ISSUE TITLE
impossible to make a single example dataloader

### ISSUE THREAD

**Issue by lengstrom** [libffcv/ffcv#186]
I get this error when I try to make a dataloader with only a single index: (i.e. any dataloader with `indices=[0]`)

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/mnt/nfs/home/engstrom/conda_envs/ffcvrgb/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/mnt/nfs/home/engstrom/conda_envs/ffcvrgb/lib/python3.9/site-packages/ffcv/loader/epoch_iterator.py", line 79, in run
    result = self.run_pipeline(b_ix, ixes, slot, events[slot])
  File "/mnt/nfs/home/engstrom/conda_envs/ffcvrgb/lib/python3.9/site-packages/ffcv/loader/epoch_iterator.py", line 141, in run_pipeline
    return tuple(x[:len(batch_indices)] for x in args)
  File "/mnt/nfs/home/engstrom/conda_envs/ffcvrgb/lib/python3.9/site-packages/ffcv/loader/epoch_iterator.py", line 141, in <genexpr>
    return tuple(x[:len(batch_indices)] for x in args)
IndexError: dimension specified as 0 but tensor has no dimensions
```

**Comment by lengstrom** [comment]
Batch size 1 in general does not work I think either

**Comment by kristian-georgiev** [comment]
happens for any batch size below 4

**Comment by kristian-georgiev** [comment]
actually, it seems dependent on batch size, e.g. `indices=[0], batch_size=1024` works (for CIFAR10 data)

**Comment by numpee** [comment]
I believe this is caused by the `Squeeze()` Operator in the pipeline (for labels). IIRC, changing to `Squeeze(0)` resolves the issue.

**Comment by GuillaumeLeclerc** [comment]
Yes @numpee  is right :)
