### ISSUE TITLE
object detection dataset

### ISSUE THREAD

**Issue by firsakov** [libffcv/ffcv#217]
Hello!

i'm trying to convert my custom object detection dataset to beton format, and get 
```
  File "/opt/conda/envs/ffcv/lib/python3.9/site-packages/ffcv/fields/basics.py", line 89, in encode
    destination[0] = field
ValueError: setting an array element with a sequence.
Process Process-1:
TypeError: only size-1 arrays can be converted to Python scalars
```

I think it could be because of labels format which return getitem method. I treid 2d numpy array, 1d numpy array (flattened my 2d array where which row has a class number and coordinates) and torch.Tensor. 
no result.
Could you help with that, what is solution for bbox labels?

**Comment by andrewilyas** [comment]
Hi @firsakov ! Can you provide a larger code sample that shows what your dataset is returning?

**Comment by firsakov** [comment]
@andrewilyas this is the error
```
File "/opt/conda/envs/ffcv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/ffcv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/ffcv/lib/python3.9/site-packages/ffcv/writer.py", line 112, in worker_job_indexed_dataset
    handle_sample(sample, dest_ix, field_names, metadata, allocator, fields)
  File "/opt/conda/envs/ffcv/lib/python3.9/site-packages/ffcv/writer.py", line 50, in handle_sample
    field.encode(destination, field_value, allocator.malloc)
  File "/opt/conda/envs/ffcv/lib/python3.9/site-packages/ffcv/fields/ndarray.py", line 93, in encode
    data_region[:] = field.reshape(-1).view('<u1')
ValueError: could not broadcast input array from shape (60,) into shape (400,)
```

and this is code
```
    writer = DatasetWriter(write_path, {
        'image': RGBImageField(),
        'label': NDArrayField(shape=(15, 5), dtype=np.dtype('float32')),
    })
    writer.from_indexed_dataset(dataset)
    batch_size = min(batch_size, len(dataset))
    nw = min([os.cpu_count(), batch_size if batch_size > 1 else 0, workers])  # number of workers
    decoder = RandomResizedCropRGBImageDecoder((224, 224))
    image_pipeline = [decoder, Cutout(), ToTensor(), ToTorchImage(), ToDevice(0)]
    label_pipeline = [IntDecoder(), ToTensor(), ToDevice(0)]
    pipelines = {
        'image': image_pipeline,
        'label': label_pipeline
    }
    loader = Loader(write_path, batch_size=bs, num_workers=num_workers,
                    order=OrderOption.RANDOM, pipelines=pipelines)
```

**Comment by andrewilyas** [comment]
Hi @firsakov , thanks for the info---can you also provide the definition of `dataset` in your code above?

**Comment by gaceladri** [comment]
Hi I'm having a similar error.

My code:
```
from ffcv.writer import DatasetWriter
from ffcv.fields import NDArrayField, FloatField, RGBImageField


writer = DatasetWriter(
    "data.beton",
    {
        "input_ids": NDArrayField(shape=(20,), dtype=np.dtype('uint8')),
        "attention_mask": NDArrayField(shape=(20,), dtype=np.dtype('uint8')),
        # Roughly 25% of the images will be stored in raw and the other in jpeg
        "pixel_values": RGBImageField(
            write_mode="proportion",  
            compress_probability=0.25,  
            max_resolution=(224, 224), 
            jpeg_quality=50,  
        ),
    },
    num_workers=20,
)

class CaptionDataset:
    def __init__(self):
        self.captions = p **# <- a pandas dataframe with 3 columns**

    def __getitem__(self, idx):
        inpt = self.captions['input_ids'][idx]   # example: [0, 1832, 27172, 161, 142555, 148, 184359, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
        at_mk = self.captions['attention_mask'][idx]   # example: [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        img = self.captions['pixel_values'][idx]       # an image of (3, 224, 224)
        return inpt, at_mk, img

    def __len__(self):
        return len(self.captions)
    
ds = CaptionDataset()
writer.from_indexed_dataset(ds)
```

The error:
```

Process Process-381:
Traceback (most recent call last):
  File "/anaconda3/envs/embedoor/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/anaconda3/envs/embedoor/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/embedoor/lib/python3.8/site-packages/ffcv/writer.py", line 112, in worker_job_indexed_dataset
    handle_sample(sample, dest_ix, field_names, metadata, allocator, fields)
  File "/anaconda3/envs/embedoor/lib/python3.8/site-packages/ffcv/writer.py", line 50, in handle_sample
    field.encode(destination, field_value, allocator.malloc)
  File "/anaconda3/envs/embedoor/lib/python3.8/site-packages/ffcv/fields/ndarray.py", line 93, in encode
    data_region[:] = field.reshape(-1).view('<u1')
ValueError: could not broadcast input array from shape (80,) into shape (20,)
```

I have confirmed that all my examples are len = 20. Did I do something wrong? Thanks!

**Comment by andrewilyas** [comment]
Assuming this is resolved (wrong dtype) and closing -- feel free to re-open a new issue if it's not resolved!
