### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [libffcv/ffcv#220]
Hi, I'm trying to load my dataset. 
Each sample of my dataset is an RGB image (fixed shape)+ np.array with fixed shape too.

I converted to .beton file. 

But when I try to load data to train with following loaders:

```
image_pipeline: List[Operation] = [
                            SimpleRGBImageDecoder(), 
                            ToTensor(), 
                            ToDevice(torch.device('cuda:0')),
                            ToTorchImage(),
                            NormalizeImage(IMAGENET_MEAN, IMAGENET_STD, np.float16)
                                ]

    train_loader = Loader('../../../data/syn_lpr_ffcv.beton', batch_size=2,
                    num_workers=cfg.DATALOADER.NUM_WORKERS, 
                    order=OrderOption.RANDOM, 
                    os_cache=False,
                    pipelines={
                        'image': image_pipeline,
                        'label': [NDArrayDecoder(), ToTensor(), ToDevice(torch.device('cuda:0'))]
                    })

    val_loader = Loader('../../../data/syn_lpr_ffcv.beton', batch_size=2,
                    num_workers=cfg.DATALOADER.NUM_WORKERS, 
                    order=OrderOption.SEQUENTIAL, 
                    os_cache=False,
                    pipelines={
                        'image': image_pipeline,
                        'label': [NDArrayDecoder(), ToTensor(), ToDevice(torch.device('cuda:0'))]
                    })
```

It creates error: 
```
Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main()
  File "tools/train.py", line 111, in main
    train(cfg)
  File "tools/train.py", line 52, in train
    train_loader = Loader('../../../data/syn_lpr_ffcv.beton', batch_size=2,
  File "/workspace/ffcv/ffcv/loader/loader.py", line 199, in __init__
    self.pipelines[field_name] = Pipeline(operations)
  File "/workspace/ffcv/ffcv/pipeline/pipeline.py", line 25, in __init__
    self.operation_blocks, _ = self.parse_pipeline()
  File "/workspace/ffcv/ffcv/pipeline/pipeline.py", line 42, in parse_pipeline
    current_state, memory_allocation = operation.declare_state_and_memory(
  File "/workspace/ffcv/ffcv/fields/rgb_image.py", line 95, in declare_state_and_memory
    max_width = widths.max()
  File "/home/thanhnv/.local/lib/python3.8/site-packages/numpy/core/_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

How can I solve this?

**Comment by andrewilyas** [comment]
Hi @NguyenVanThanhHust ! Can you give us some more information about your dataset, for example, the code you used to write it?

**Comment by NguyenVanThanhHust** [comment]
Sorry, I don't keep the code to use it anymore. I just you pytorch_lighting instead of.
