### ISSUE TITLE
Unsupported Image type 

### ISSUE THREAD

**Issue by shashankvasisht** [libffcv/ffcv#57]
Hi I was following your tutorial and I passed a pytorch Tensor as a image file in the data loader, but I got the following error:

```
Process Process-1:
Traceback (most recent call last):
  File "/home/qblocks/instance6/mohit/anaconda3/envs/ffcv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/qblocks/instance6/mohit/anaconda3/envs/ffcv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/qblocks/instance6/mohit/anaconda3/envs/ffcv/lib/python3.9/site-packages/ffcv/writer.py", line 112, in worker_job_indexed_dataset
    handle_sample(sample, dest_ix, field_names, metadata, allocator, fields)
  File "/home/qblocks/instance6/mohit/anaconda3/envs/ffcv/lib/python3.9/site-packages/ffcv/writer.py", line 50, in handle_sample
    field.encode(destination, field_value, allocator.malloc)
  File "/home/qblocks/instance6/mohit/anaconda3/envs/ffcv/lib/python3.9/site-packages/ffcv/fields/rgb_image.py", line 325, in encode
    raise TypeError(f"Unsupported image type {type(image)}")
TypeError: Unsupported image type <class 'str'>
```

Here is my code snippet :

``` 
    tr_dataset_func = datasets.COCO('train',args)
    vl_dataset_func = datasets.COCO('train',args)

    train_write_path = "/home/qblocks/instance6/shashank/Development/Watermark_removal/DBWR/DBWR_ffcv/ffcv_data/train/train.beton"
    val_write_path = "/home/qblocks/instance6/shashank/Development/Watermark_removal/DBWR/DBWR_ffcv/ffcv_data/val/val.beton"

    train_writer = DatasetWriter(train_write_path, {"image": RGBImageField(),
                    "target": RGBImageField(), 
                    }, num_workers=1)
    
    val_writer = DatasetWriter(val_write_path, {"image": RGBImageField(),
                    "target": RGBImageField(), 
                    }, num_workers=1)


    train_writer.from_indexed_dataset(tr_dataset_func)
    val_writer.from_indexed_dataset(vl_dataset_func)

```

Here is my return dict from my dataset class : 

```

        return {
                "image": img_wm_t,
                "target": img_t, 
                }

```

where both img_wm_t and img_t are pytorch tensors.

Also what Field should I use if i want to return string path from my Dataset class ??

**Comment by andrewilyas** [comment]
Hi @shashankvasisht ! I'm not too familiar with the torchvision COCO dataset, do you think you could print the output of ``print(tr_dataset_func[0])``, and also paste in what ``args`` is?

As for strings, here is a minimal example:
```python
import numpy as np
from uuid import uuid4
from ffcv.writer import DatasetWriter
from ffcv.fields import NDArrayField
from ffcv.loader import Loader, OrderOption
from ffcv.fields.decoders import NDArrayDecoder
from tempfile import NamedTemporaryFile

MAX_STRING_SIZE = 100

class CaptionDataset:
    def __init__(self, N):
        self.captions = [str(uuid4())[:np.random.randint(50)] for _ in range(N)]

    def __getitem__(self, idx):
        padded_caption = (self.captions[idx] + (" " * MAX_STRING_SIZE))[:MAX_STRING_SIZE]
        return (np.frombuffer(padded_caption.encode('ascii'), dtype='uint8'),)

    def __len__(self):
        return len(self.captions)

dataset = CaptionDataset(100)

with NamedTemporaryFile() as handle:
    writer = DatasetWriter(handle.name, {
        'label': NDArrayField(np.dtype('uint8'), (MAX_STRING_SIZE,))
    }, num_workers=1)

    writer.from_indexed_dataset(dataset)

    loader = Loader(handle.name,
                batch_size=10,
                num_workers=2,
                order=OrderOption.RANDOM,
                pipelines={
                    'label': [NDArrayDecoder()]
                })

    for x, in loader:
        for cap in x:
            print(cap.tobytes().decode('ascii').strip())
```

**Comment by GuillaumeLeclerc** [comment]
Hopefully this was helpful to you @shashankvasisht. If you have more questions feel free to reopen. I'll close in the meantime

**Comment by axkoenig** [comment]
Attaching a minimal example of encoding a dataset of strings with FFCV. Please correct me if there is a nicer way to implement this. Note, the data items must be tuples. Also, `Loader` seems to automatically pad, so no need to pad manually as shown above.

```python
import numpy as np

from ffcv.writer import DatasetWriter
from ffcv.fields import BytesField
from ffcv.loader import Loader

ENC = "utf-8"
DATA_PATH = "data.beton"


def encode(s: str):
    return np.frombuffer(s.encode(ENC), dtype="uint8")


data = [(encode("hello"),), (encode("world!!"),), (encode("how is life"),)]

writer = DatasetWriter(DATA_PATH, {"text": BytesField()})
writer.from_indexed_dataset(data)

loader = Loader(DATA_PATH, batch_size=1)

for item in loader:
    print("raw out\t", item)
    print("decoded\t", item[0].numpy().tobytes().decode(ENC))
```
Prints 
```
raw out  (tensor([[104, 101, 108, 108, 111,   0,   0,   0,   0,   0,   0]], dtype=torch.uint8),)
decoded  hello
raw out  (tensor([[119, 111, 114, 108, 100,  33,  33,   0,   0,   0,   0]], dtype=torch.uint8),)
decoded  world!!
raw out  (tensor([[104, 111, 119,  32, 105, 115,  32, 108, 105, 102, 101]], dtype=torch.uint8),)
decoded  how is life
```

**Comment by axkoenig** [comment]
This is how to achieve the same with JSONField.

```python
import numpy as np

from ffcv.writer import DatasetWriter
from ffcv.fields import JSONField
from ffcv.loader import Loader

ENC = "utf-8"
DATA_PATH = "data.beton"


def encode(s: str):
    return np.frombuffer(s.encode(ENC), dtype="uint8")


data = [("hello",), ("world",), ("how is life",)]

writer = DatasetWriter(DATA_PATH, {"text": JSONField()})
writer.from_indexed_dataset(data)

loader = Loader(DATA_PATH, batch_size=1)

for item in loader:
    print("raw out\t", item)
    print("decoded\n", JSONField.unpack(item[0])[0])
```

**Comment by BraSDon** [comment]
@axkoenig I tried to use your script regarding a text dataset. However I seem to non-deterministicly fail decoding. I used the exact same code except for masking the CUDA_VISIBLE_DEVICES, as I have a CUDA device I wish not to use.

The decoding fails at a different point each time I execute it.

Examples:
```
raw out  (tensor([[104, 101, 108, 108, 111,   0,   0,   0, 113,   0,   0]],
       dtype=torch.uint8),)
decoded  helloq
raw out  (tensor([[119, 111, 114, 108, 100,  33,  33, 216,   7,   0,   0]],
       dtype=torch.uint8),)
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    print("decoded\t", item[0].numpy().tobytes().decode(ENC))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 7: invalid continuation byte
```

```
raw out  (tensor([[104, 101, 108, 108, 111, 127,   0,   0,  64, 172,  52]],
       dtype=torch.uint8),)
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    print("decoded\t", item[0].numpy().tobytes().decode(ENC))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 9: invalid start byte
```

@GuillaumeLeclerc Are you aware of any changes to the library that could cause the different behavior? Or is it likely to be a setup issue?

**Comment by JRopes** [comment]
I am also struggling with this original issue and it seems it was not really answered. For some reason I keep getting this "TypeError: Unsupported image type <class 'str'>" error despite me only saving images. Can anybody help me with this?
